name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/original-owner/original-repo.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Configure Git User
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"

      - name: Merge Upstream into Fork
        run: git merge upstream/master --allow-unrelated-histories

      - name: Push Changes to Fork
        run: git push origin master
