name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/micartey/webhookly.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream into Fork
        run: git merge upstream/master --allow-unrelated-histories

      - name: Push Changes to Fork
        run: git push origin master
        env:
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
